security:
    password_hashers:
        App\Entity\User:
            algorithm: 'auto'
            cost: 4

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            provider: app_user_provider
            user_checker: App\Security\AppUserChecker # pour la confirmation de mail
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: home
            logout:
                path: app_logout
                target: home

    role_hierarchy:
        ROLE_CUSTOMER: []
        ROLE_CRAFTSMAN: [ROLE_CUSTOMER]

    access_control:
        - { path: ^/cart, roles: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/product/add, roles: ROLE_CRAFTSMAN }
        - { path: ^/order, roles: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/login_app, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/public_route, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # autres routes
